# Generated by Django 3.0.8 on 2020-07-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200729_2334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
