# Generated by Django 3.0.8 on 2020-07-30 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200730_1148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
