# Generated by Django 3.0.8 on 2020-07-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200730_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='num',
            new_name='code',
        ),
    ]
