# Generated by Django 3.0.8 on 2020-07-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200730_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='num',
            new_name='code',
        ),
    ]
