# Generated by Django 3.0.8 on 2020-07-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200730_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.SlugField(default='', max_length=150),
        ),
    ]
