# Generated by Django 3.0.8 on 2020-07-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200731_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
